[2024-11-14T22:01:38.299+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: build_elt_dbt.dbt_cloud manual__2024-11-14T22:01:36.499532+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
